//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Property_Management.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WuyeProjectEntities : DbContext
    {
        public WuyeProjectEntities()
            : base("name=WuyeProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<w_admin> w_admin { get; set; }
        public virtual DbSet<w_announcement> w_announcement { get; set; }
        public virtual DbSet<w_building> w_building { get; set; }
        public virtual DbSet<w_complaint> w_complaint { get; set; }
        public virtual DbSet<w_device> w_device { get; set; }
        public virtual DbSet<w_house> w_house { get; set; }
        public virtual DbSet<w_installation> w_installation { get; set; }
        public virtual DbSet<w_packing> w_packing { get; set; }
        public virtual DbSet<w_property_user> w_property_user { get; set; }
        public virtual DbSet<w_repair> w_repair { get; set; }
        public virtual DbSet<w_room> w_room { get; set; }
        public virtual DbSet<w_room_info> w_room_info { get; set; }
        public virtual DbSet<w_system_params> w_system_params { get; set; }
        public virtual DbSet<w_user> w_user { get; set; }
        public virtual DbSet<w_user_paymoney> w_user_paymoney { get; set; }
    }
}
