//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Property_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_building
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public w_building()
        {
            this.w_house = new HashSet<w_house>();
            this.w_repair = new HashSet<w_repair>();
            this.w_user = new HashSet<w_user>();
        }
    
        public int id { get; set; }
        public string room_name { get; set; }
        public Nullable<int> floors { get; set; }
        public Nullable<decimal> height { get; set; }
        public Nullable<decimal> area { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<int> sp_id { get; set; }
        public string remark { get; set; }
    
        public virtual w_system_params w_system_params { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<w_house> w_house { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<w_repair> w_repair { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<w_user> w_user { get; set; }
    }
}
