//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Property_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_complaint
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> uid { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string describe { get; set; }
        public string state { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string title { get; set; }
        public Nullable<int> is_use { get; set; }
        public string result { get; set; }
        public Nullable<int> house_id { get; set; }
        public string pass_detail { get; set; }
    
        public virtual w_house w_house { get; set; }
    }
}
