//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Property_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_device
    {
        public int id { get; set; }
        public Nullable<long> device_id { get; set; }
        public string device_name { get; set; }
        public string device_desc { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
    }
}
