//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Property_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_house
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public w_house()
        {
            this.w_complaint = new HashSet<w_complaint>();
            this.w_repair = new HashSet<w_repair>();
            this.w_user_paymoney = new HashSet<w_user_paymoney>();
            this.w_user = new HashSet<w_user>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public int b_id { get; set; }
        public int d_id { get; set; }
        public Nullable<int> d_room { get; set; }
        public int c_id { get; set; }
        public Nullable<int> r_id { get; set; }
        public Nullable<int> g_id { get; set; }
        public Nullable<int> bz_id { get; set; }
        public Nullable<decimal> area { get; set; }
        public Nullable<decimal> use_area { get; set; }
        public Nullable<int> is_use { get; set; }
    
        public virtual w_building w_building { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<w_complaint> w_complaint { get; set; }
        public virtual w_system_params w_system_params { get; set; }
        public virtual w_system_params w_system_params1 { get; set; }
        public virtual w_system_params w_system_params2 { get; set; }
        public virtual w_system_params w_system_params3 { get; set; }
        public virtual w_system_params w_system_params4 { get; set; }
        public virtual w_system_params w_system_params5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<w_repair> w_repair { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<w_user_paymoney> w_user_paymoney { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<w_user> w_user { get; set; }
    }
}
