//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Property_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_property_user
    {
        public int id { get; set; }
        public string wy_number { get; set; }
        public string name { get; set; }
        public int sex { get; set; }
        public string work_name { get; set; }
        public string id_number { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string pic { get; set; }
        public string work_info { get; set; }
    }
}
