//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Property_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_room
    {
        public int id { get; set; }
        public string room_id { get; set; }
        public string floor { get; set; }
        public string owner { get; set; }
        public string phone { get; set; }
        public string type { get; set; }
        public string construction_area { get; set; }
        public string actual_area { get; set; }
        public string home_state { get; set; }
    }
}
