//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Property_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public w_user()
        {
            this.w_packing = new HashSet<w_packing>();
            this.w_repair = new HashSet<w_repair>();
        }
    
        public int id { get; set; }
        public Nullable<int> building_id { get; set; }
        public Nullable<int> danyuan_id { get; set; }
        public Nullable<int> house_id { get; set; }
        public string user_name { get; set; }
        public string house_number { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string id_number { get; set; }
        public string work_address { get; set; }
        public string link_address { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string remark { get; set; }
        public string createtime { get; set; }
    
        public virtual w_building w_building { get; set; }
        public virtual w_house w_house { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<w_packing> w_packing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<w_repair> w_repair { get; set; }
        public virtual w_system_params w_system_params { get; set; }
    }
}
